### PR TITLE
Pull in everything mistakenly pushed to main

### PR DESCRIPTION
**Pull request by danhunsaker**
New commits should go to `develop`. That includes PRs.

### CODE REVIEW

**Comment by pprkut** [comment]
Oh sorry! I somehow was under the impression `develop` had been a temporary integration branch for all the PRs from the old repo. My bad! Should I recreate the still open pull requests?

**Review by pprkut — APPROVED** [review]

**Comment by danhunsaker** [comment]
Yeah, i just needed to be paying more attention when merging stuff. 😅

**Comment by pprkut** [comment]
@danhunsaker ping :slightly_smiling_face:

**Comment by pprkut** [comment]
@danhunsaker Is there any way we could move this along? The way things are now this repo looks as abandoned as the previous one, which would be a shame :confused: 

I created a branch now in my repo that combines all the changes I need at work, but that's not really a long-term solution. There's some other people who mentioned they forked it already too. I would hate to see the community splinter any further.

**Comment by pprkut** [comment]
@danhunsaker Any chance you could add me to the team? Then I could start merging some of the open reviews. I really want to try everything to keep this repo alive rather than creating a new fork.

**Comment by danhunsaker** [comment]
Been waiting for an approval from someone on the team, but it hasn't happened... Trying to work around the requirement now.

**Pull request merged**
