### PR TITLE
*scan commands are broken with new(er) credis

### PR DESCRIPTION
**Pull request by prestonbrown**
make the scan commands pass their first arg (the cursor) as a reference, as is required.

### CODE REVIEW

**Comment by danhunsaker** [comment]
We don't use the `*scan` commands in PHP-Resque, so this appears to be out of scope for us to fix. This would be a great PR for Credis itself, though!

**Comment by prestonbrown** [comment]
Dan,

If for some reason you need to scan on the redis you are using resque for,
getting the redis instance from resque seems to make sense. But with __call
being written the way it is, scan is broken.

What's the harm / consequence that you foresee?

Preston

**Comment by danhunsaker** [comment]
We're going to refactor things so that you provide a Redis library, rather than the other way around.

**Comment by prestonbrown** [comment]
Sounds good to me.

Preston

**Comment by danhunsaker** [comment]
I added the rest of this after accidentally hitting Comment, so for the benefit of your email records, here's the rest of what I said:

So I'd like to avoid changes that won't apply across providers.

Also, passing references from inside Resque won't actually work in any case, as the variables you want to work with are still being passed by value _into_ Resque. So there's still no way to retrieve the result afterward.

(I'll be deleting this comment shortly so it only shows in emails.)

**Pull request closed without merging**
